# Generated by Django 5.1 on 2025-11-09 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Điểm tai nạn')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('accident_type', models.CharField(choices=[('xe_may', 'Tai nạn xe máy'), ('o_to', 'Tai nạn ô tô'), ('xe_tai', 'Tai nạn xe tải'), ('nguoi_di_bo', 'Tai nạn người đi bộ'), ('khac', 'Loại khác')], max_length=50, verbose_name='Loại tai nạn')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian')),
                ('damage_level', models.CharField(choices=[('nhe', 'Nhẹ'), ('trung_binh', 'Trung bình'), ('nang', 'Nặng'), ('rat_nang', 'Rất nặng')], max_length=50, verbose_name='Mức độ thiệt hại')),
                ('district', models.CharField(choices=[('ninh_kieu', 'Ninh Kiều'), ('cai_rang', 'Cái Răng'), ('binh_thuy', 'Bình Thủy'), ('o_mon', 'Ô Môn'), ('thot_not', 'Thốt Nốt'), ('phong_dien', 'Phong Điền'), ('co_do', 'Cờ Đỏ'), ('vinh_thanh', 'Vĩnh Thạnh'), ('thoi_lai', 'Thới Lai')], max_length=100, verbose_name='Quận/Huyện')),
            ],
            options={
                'verbose_name': 'Vụ tai nạn',
                'verbose_name_plural': 'Các vụ tai nạn',
                'db_table': 'accidents',
                'ordering': ['-datetime'],
            },
        ),
    ]
