# Generated by Django 5.0.8 on 2025-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='district',
        ),
        migrations.AddField(
            model_name='accident',
            name='commune_code',
            field=models.CharField(blank=True, help_text='Ví dụ: 81519002', max_length=20, null=True, verbose_name='Mã Phường/Xã'),
        ),
    ]
